package DCMSApp;


/**
* DCMSApp/DCMS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dcms.idl
* Saturday, June 16, 2018 11:45:16 o'clock AM EDT
*/

public interface DCMS extends DCMSOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DCMS
