package DCMSApp;


/**
* DCMSApp/DCMSOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dcms.idl
* Saturday, June 16, 2018 11:45:16 o'clock AM EDT
*/

public interface DCMSOperations 
{
  boolean createTRecord (String firstName, String lastName, String address, String phone, String specialization, String location);
  boolean createSRecord (String firstName, String lastName, String courseRegistered, String status, int statusDate);
  String[] getRecordCounts ();
  boolean editRecord (String recordID, String fieldName, String newValue);
  boolean transferRecord (String managerId, String recordId, String remoteCenterLocation);
  void shutdown ();
} // interface DCMSOperations
