package DCMSApp;


/**
* DCMSApp/DCMSOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dcms.idl
* Friday, June 15, 2018 5:28:43 o'clock AM EDT
*/

public interface DCMSOperations 
{
  boolean createTRecord (String firstName, String lastName, String address, String phone, String specialization, String location);
  boolean createSRecord ();
  String[] getRecordCounts ();
  boolean editRecord ();
  boolean transferRecord (String managerId, String recordId, String remoteCenterLocation);
  void shutdown ();
} // interface DCMSOperations
