package DCMSApp;


/**
* DCMSApp/stringarrayHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dcms.idl
* Saturday, June 16, 2018 11:45:16 o'clock AM EDT
*/

public final class stringarrayHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public stringarrayHolder ()
  {
  }

  public stringarrayHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DCMSApp.stringarrayHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DCMSApp.stringarrayHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DCMSApp.stringarrayHelper.type ();
  }

}
