package CorbaApp;

/**
* CorbaApp/DCMSHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Interface.idl
* Wednesday, 13 June, 2018 8:12:02 PM AKDT
*/

public final class DCMSHolder implements org.omg.CORBA.portable.Streamable
{
  public CorbaApp.DCMS value = null;

  public DCMSHolder ()
  {
  }

  public DCMSHolder (CorbaApp.DCMS initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CorbaApp.DCMSHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CorbaApp.DCMSHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CorbaApp.DCMSHelper.type ();
  }

}
