module DCMSApp{
	typedef sequence<string> stringarray;
	interface DCMS { 
	boolean createTRecord(in string firstName,in string lastName,in string address,in string phone,in string specialization,in string location);
	boolean createSRecord(in string firstName,in string lastName,in string courseRegistered,in string status,in long statusDate);
	stringarray getRecordCounts();
	boolean editRecord(in string recordID,in string fieldName,in string newValue);
	boolean transferRecord(in string managerId, in string recordId, in string remoteCenterLocation);
	oneway void shutdown();
	};
};
