module DCMSApp{
	typedef sequence<string> stringarray;
	interface DCMS { 
	boolean createTRecord(in string firstName,in string lastName,in string address,in string phone,in string specialization,in string location);
	boolean createSRecord();
	stringarray getRecordCounts();
	boolean editRecord();
	boolean transferRecord(in string managerId, in string recordId, in string remoteCenterLocation);
	oneway void shutdown();
	};
};
