
package client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DCMSInterface", targetNamespace = "http://com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DCMSInterface {


    /**
     * 
     * @param statusDate
     * @param firstName
     * @param lastName
     * @param managerID
     * @param coursesRegistered
     * @param status
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createSRecord", targetNamespace = "http://com/", className = "client.CreateSRecord")
    @ResponseWrapper(localName = "createSRecordResponse", targetNamespace = "http://com/", className = "client.CreateSRecordResponse")
    @Action(input = "http://com/DCMSInterface/createSRecordRequest", output = "http://com/DCMSInterface/createSRecordResponse")
    public String createSRecord(
        @WebParam(name = "ManagerID", targetNamespace = "")
        String managerID,
        @WebParam(name = "FirstName", targetNamespace = "")
        String firstName,
        @WebParam(name = "LastName", targetNamespace = "")
        String lastName,
        @WebParam(name = "CoursesRegistered", targetNamespace = "")
        String coursesRegistered,
        @WebParam(name = "Status", targetNamespace = "")
        String status,
        @WebParam(name = "StatusDate", targetNamespace = "")
        String statusDate);

    /**
     * 
     * @param firstName
     * @param lastName
     * @param address
     * @param phone
     * @param specialization
     * @param location
     * @param managerID
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createTRecord", targetNamespace = "http://com/", className = "client.CreateTRecord")
    @ResponseWrapper(localName = "createTRecordResponse", targetNamespace = "http://com/", className = "client.CreateTRecordResponse")
    @Action(input = "http://com/DCMSInterface/createTRecordRequest", output = "http://com/DCMSInterface/createTRecordResponse")
    public String createTRecord(
        @WebParam(name = "ManagerID", targetNamespace = "")
        String managerID,
        @WebParam(name = "FirstName", targetNamespace = "")
        String firstName,
        @WebParam(name = "LastName", targetNamespace = "")
        String lastName,
        @WebParam(name = "Address", targetNamespace = "")
        String address,
        @WebParam(name = "Phone", targetNamespace = "")
        String phone,
        @WebParam(name = "Specialization", targetNamespace = "")
        String specialization,
        @WebParam(name = "Location", targetNamespace = "")
        String location);

    /**
     * 
     * @param recordID
     * @param newServerName
     * @param managerID
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "transferRecord", targetNamespace = "http://com/", className = "client.TransferRecord")
    @ResponseWrapper(localName = "transferRecordResponse", targetNamespace = "http://com/", className = "client.TransferRecordResponse")
    @Action(input = "http://com/DCMSInterface/transferRecordRequest", output = "http://com/DCMSInterface/transferRecordResponse")
    public String transferRecord(
        @WebParam(name = "ManagerID", targetNamespace = "")
        String managerID,
        @WebParam(name = "RecordID", targetNamespace = "")
        String recordID,
        @WebParam(name = "NewServerName", targetNamespace = "")
        String newServerName);

    /**
     * 
     * @param managerID
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRecordCounts", targetNamespace = "http://com/", className = "client.GetRecordCounts")
    @ResponseWrapper(localName = "getRecordCountsResponse", targetNamespace = "http://com/", className = "client.GetRecordCountsResponse")
    @Action(input = "http://com/DCMSInterface/getRecordCountsRequest", output = "http://com/DCMSInterface/getRecordCountsResponse")
    public String getRecordCounts(
        @WebParam(name = "ManagerID", targetNamespace = "")
        String managerID);

    /**
     * 
     * @param recordID
     * @param newValue
     * @param fieldName
     * @param managerID
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "editRecord", targetNamespace = "http://com/", className = "client.EditRecord")
    @ResponseWrapper(localName = "editRecordResponse", targetNamespace = "http://com/", className = "client.EditRecordResponse")
    @Action(input = "http://com/DCMSInterface/editRecordRequest", output = "http://com/DCMSInterface/editRecordResponse")
    public String editRecord(
        @WebParam(name = "ManagerID", targetNamespace = "")
        String managerID,
        @WebParam(name = "RecordID", targetNamespace = "")
        String recordID,
        @WebParam(name = "FieldName", targetNamespace = "")
        String fieldName,
        @WebParam(name = "NewValue", targetNamespace = "")
        String newValue);

}
