
package client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MTLImplService", targetNamespace = "http://com/", wsdlLocation = "http://localhost:7777/mtl?wsdl")
public class MTLImplService
    extends Service
{

    private final static URL MTLIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException MTLIMPLSERVICE_EXCEPTION;
    private final static QName MTLIMPLSERVICE_QNAME = new QName("http://com/", "MTLImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:7777/mtl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MTLIMPLSERVICE_WSDL_LOCATION = url;
        MTLIMPLSERVICE_EXCEPTION = e;
    }

    public MTLImplService() {
        super(__getWsdlLocation(), MTLIMPLSERVICE_QNAME);
    }

    public MTLImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MTLIMPLSERVICE_QNAME, features);
    }

    public MTLImplService(URL wsdlLocation) {
        super(wsdlLocation, MTLIMPLSERVICE_QNAME);
    }

    public MTLImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MTLIMPLSERVICE_QNAME, features);
    }

    public MTLImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MTLImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DCMSInterface
     */
    @WebEndpoint(name = "MTLImplPort")
    public DCMSInterface getMTLImplPort() {
        return super.getPort(new QName("http://com/", "MTLImplPort"), DCMSInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DCMSInterface
     */
    @WebEndpoint(name = "MTLImplPort")
    public DCMSInterface getMTLImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://com/", "MTLImplPort"), DCMSInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MTLIMPLSERVICE_EXCEPTION!= null) {
            throw MTLIMPLSERVICE_EXCEPTION;
        }
        return MTLIMPLSERVICE_WSDL_LOCATION;
    }

}
